# 13F Backtest -- EXAMPLE
SEC_BASE_URL = 'https://data.sec.gov'
SEC_USER_AGENT = 'Your Name your@email.com'
SEC_REQUEST_DELAY = 0.15
THIRTEENF_DB = 'thirteenf_data.db'
MIN_NEW_INITIATIONS = 2
MIN_POSITION_VALUE = 1000000
MIN_MARKET_CAP = 500000000
ENTRY_DELAY_DAYS = 1
HOLD_PERIODS = [4, 8, 13, 26]
BACKTEST_START = '2018-01-01'
BACKTEST_END = None
COLLECT_QUARTERS = 28
RESULTS_DIR = 'results'
